services:
  mysql:
    image: mysql:8.0
    env_file:
      - ".env"
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_bin
    - --skip-character-set-client-handshake
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/config:/etc/mysql/conf.d
    - ./db/files:/var/lib/mysql-files
    - ./db/logs:/var/log/mysql
 
  jira:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JIRA_VERSION: ${JIRA_VERSION}
        MYSQL_VERSION: ${MYSQL_VERSION}

    env_file:
      - ".env"
    image: ghcr.io/declue/docker_jira:main
    ports:
      - "8080:8080"
    volumes:
      - ./jira/certs:/etc/certs
      - ./jira/data:/var/atlassian/jira
    logging:
      driver: "json-file"
      options:
          max-size: "100m"

