
services:
  jira:
    build: .
    image: declue/jira:9.5.0
    container_name: myjira
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/etc/certs
      - ./data:/var/atlassian/jira
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
